import datetime

AOV_Schema = [
    "OBJECTID",
    "Proj_Award",
    "Proj_Funding_Country",
    "Proj_Funding_Agency",
    "Proj_Program_Code",
    "Proj_Start_Year",
    "Proj_End_Year",
    "Proj_Title",
    "Proj_AON",
    "Proj_Initiative",
    "Proj_Discipline",
    "Proj_Institution",
    "Proj_Contact_Name",
    "Proj_Contact_Email",
    "Proj_Contact_Phone",
    "Proj_Contact_Role",
    "Proj_Page_Link",
    "Proj_Metadata_Link",
    "Site_Name",
    "Site_ID_AOV",
    "Site_ID_Alt1",
    "Site_ID_Alt2",
    "Site_Country",
    "Site_Place",
    "Site_Lat",
    "Site_Long",
    "Site_Accuracy",
    "Site_Depth",
    "Site_Elevation",
    "Site_Start_Date",
    "Site_End_Date",
    "Site_Type",
    "Site_GCMD_Science",
    "Site_GCMD_Platform",
    "Site_GCMD_Instrument",
    "Data_Page_Link1",
    "Data_Page_Link2",
    "Data_Metadata_Link",
    "db_Metadata_Sources",
    "db_Metadata_Wrangler",
    "db_Date_Created",
    "db_Date_Export",
    "db_Date_Modified",
    "db_Notes",
    "Site_Name_IDs",
    "Site_Lat_Long",
    "Site_Location_Country",
    "Site_Abstract",
    "Site_ID_BAID",
    "Site_Start_Year",
    "Site_End_Year",
]

aov_hardcode_values = {
    "OBJECTID":"",
    "Proj_Award": "",
    "Proj_Funding_Country": "United States of America",
    "Proj_Funding_Agency": "",
    "Proj_Program_Code": "",
    "Proj_Start_Year": "",
    "Proj_End_Year": "",
    "Proj_Title": "",
    "Proj_AON": "",
    "Proj_Initiative": "",
    "Proj_Discipline": "",
    "Proj_Institution": "",
    "Proj_Contact_Name": "",
    "Proj_Contact_Email": "",
    "Proj_Contact_Phone": "",
    "Proj_Contact_Role": "Principal Investigator",
    "Proj_Page_Link": "",
    "Proj_Metadata_Link": "",
    "Site_Name": "Logistics Base",
    "Site_ID_AOV": "",
    "Site_ID_Alt1": "",
    "Site_ID_Alt2": "",
    "Site_Country": "",
    "Site_Place": "",
    "Site_Lat": "",
    "Site_Long": "",
    "Site_Accuracy": "",
    "Site_Depth": "",
    "Site_Elevation": "",
    "Site_Start_Date": "",
    "Site_End_Date": "",
    "Site_Type": "",
    "Site_GCMD_Science": "",
    "Site_GCMD_Platform": "",
    "Site_GCMD_Instrument": "",
    "Data_Page_Link1": "",
    "Data_Page_Link2": "",
    "Data_Metadata_Link": "",
    "db_Metadata_Sources": "ARMAPasTEXT",
    "db_Metadata_Wrangler": "ARMAP_To_AOV_DataPull",
    "db_Date_Created": datetime.datetime.today().strftime("%d-%m-%Y"),
    "db_Date_Export": "",
    "db_Date_Modified": "",
    "db_Notes": "",
    "Site_Name_IDs": "",
    "Site_Lat_Long": "",
    "Site_Location_Country": "",
    "Site_Abstract": "",
    "Site_ID_BAID": "",
    "Site_Start_Year": "",
    "Site_End_Year": "",
}
